_target_: pytorch_lightning.Trainer

# default_root_dir: ${paths.logdir}

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16
accumulate_grad_batches: 1

# perform a validation loop every N training epochs
check_val_every_n_epoch: null
val_check_interval: 256
max_epochs: -1
max_steps: 12800

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
